<?php

namespace Core\MediaBundle\Helper;

use Vich\UploaderBundle\Naming\NamerInterface;
use Vich\UploaderBundle\Mapping\PropertyMapping;

class UniqNamerForImageUpload implements NamerInterface {
    
    /**
     * Returns a name generated by uniqid().
     * 
     * @param Image $object
     * @param PropertyMapping $mapping
     * @return string
     */
    public function name($object, PropertyMapping $mapping) {   
       $name = uniqid(null, true);
       $name = sprintf('%s.%s', $name, 'png');     
      
       return $name;    
    }
}


